[package]
name = "aviutl-webp-plugin"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aviutl-rs.workspace = true
dialog = "0.3.0"
sprintf = "0.1.4"
serde.workspace = true
slint = "1.3.2"
image.workspace = true
webp = "0.2.6"
